# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d53bc6274a77ace1be850ad22aba7f1e0fd089744b7650d2b957d24bd0774bde2f39c3922b505414c6468279f84ad5f916b2b0d27368693938f87acf28f5a888

test:
  secret_key_base: d2d0e2c3ae73f430b55048afe7bb9696da290a156516078c36f46733d1bcfb56ef6cb4dc9b3d68f698e8276df64850d92fe655bbad2591196c8470e62e366ae6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
